Repository pimcore/data-hub, pull requests merged in 2020-06, with the labels that each got.

#237 Decouple configuration UI from actual adapter implementation
  src/Controller/ConfigController.php
  src/Event/AdminEvents.php
  src/PimcoreDataHubBundle.php
  src/Resources/public/js/adapter/graphql.js
  src/Resources/public/js/config.js
  src/Resources/public/js/configuration/graphql/configItem.js
Labels: Task

#238 Document query: use correct tag for instanceof check to fix null attributes
  src/GraphQL/DocumentElementType/RelationsType.php
Labels: Bug

#239 Make workspace setting configurable
  src/Resources/public/js/workspace/abstract.js
Labels: Improvement
