Repository pimcore/data-hub, pull requests merged in 2020-05, with the labels that each got.

#212 Implement Client safe exceptions
  src/GraphQL/AssetType/AssetType.php
  src/GraphQL/ClassTypeDefinitions.php
  src/GraphQL/ClassificationstoreType/Feature.php
  src/GraphQL/DataObjectInputProcessor/IfEmptyOperator.php
  src/GraphQL/DataObjectInputProcessor/Image.php
  src/GraphQL/DataObjectInputProcessor/ManyToManyObjectRelation.php
  src/GraphQL/DataObjectInputProcessor/ManyToManyRelation.php
  src/GraphQL/DataObjectQueryFieldConfigGenerator/Helper/AssetBase.php
  src/GraphQL/DataObjectQueryFieldConfigGenerator/Helper/Hotspotimage.php
  src/GraphQL/DataObjectQueryFieldConfigGenerator/Helper/Href.php
  src/GraphQL/DataObjectQueryFieldConfigGenerator/Helper/ImageGallery.php
  src/GraphQL/DataObjectQueryFieldConfigGenerator/Helper/Multihref.php
  src/GraphQL/DataObjectQueryFieldConfigGenerator/Helper/MultihrefMetadata.php
  src/GraphQL/DataObjectQueryFieldConfigGenerator/Helper/Objects.php
  src/GraphQL/DataObjectQueryFieldConfigGenerator/Helper/ObjectsMetadata.php
  src/GraphQL/DataObjectQueryFieldConfigGenerator/Helper/ReverseManyToManyObjects.php
  src/GraphQL/Exception/ClientSafeException.php
  src/GraphQL/Exception/NotAllowedException.php
  src/GraphQL/FieldHelper/DataObjectFieldHelper.php
  src/GraphQL/PropertyType/AssetFolderType.php
  src/GraphQL/PropertyType/AssetType.php
  src/GraphQL/PropertyType/DataObjectType.php
  src/GraphQL/PropertyType/DocumentFolderType.php
  src/GraphQL/PropertyType/DocumentType.php
  src/GraphQL/PropertyType/ElementPropertyType.php
  src/GraphQL/PropertyType/HotspotMetadataType.php
  src/GraphQL/PropertyType/ObjectFolderType.php
  src/GraphQL/Resolver/Element.php
  src/GraphQL/Resolver/HotspotType.php
  src/GraphQL/Resolver/QueryType.php
  src/GraphQL/Resolver/Video.php
  src/GraphQL/Service.php
Labels: Improvement

#218 [Admin] Explorer - Fix open in tab
  src/Controller/ConfigController.php
  src/Controller/GraphQLExplorerController.php
  src/Resources/public/js/configItem.js
Labels: Bug

#220 asset-metadata: allow to specify language or ignore language at all
  src/GraphQL/AssetType/AssetType.php
  src/GraphQL/Resolver/AssetType.php
Labels: Improvement

#221 Add resolutions to AssetType
  doc/graphl/querysamples/Sample_GetAsset.md
  src/GraphQL/AssetType/AssetType.php
  src/GraphQL/Resolver/AssetType.php
Labels: New Feature

#222 Implement asset-listing
  doc/GraphQL.md
  doc/graphl/querysamples/Sample_GetAssetListing.md
  src/Controller/ConfigController.php
  src/GraphQL/Query/QueryType.php
  src/GraphQL/Resolver/AssetListing.php
  src/GraphQL/Resolver/AssetType.php
  src/Resources/translations/admin.en.yml
Labels: New Feature
