Repository pimcore/data-hub, pull requests merged in 2022-07, with the labels that each got.

#551 [Feature]: GraphQL Translations
  doc/10_GraphQL/04_Query/11_Query_Samples/14_Sample_GetTranslationListing.md
  src/Controller/ConfigController.php
  src/DependencyInjection/Compiler/ImportExportLocatorsPass.php
  src/GraphQL/Query/QueryType.php
  src/GraphQL/Resolver/TranslationListing.php
  src/GraphQL/Service.php
  src/GraphQL/SharedType/JsonType.php
  src/GraphQL/TranslationType/TranslationType.php
  src/Resources/config/graphql.yml
  src/Resources/translations/admin.en.yml
  tests/GraphQL/ResolveTest.php
Labels: Improvement

#558 Fix: removed excess bracket when quoting the value for "not" filter o…
  src/GraphQL/Helper.php
Labels: Bug

#560 [Improvement] Support for multiple API keys per endpoint
  doc/Installation_and_Upgrade/02_Upgrade_Notes.md
  src/Configuration.php
  src/Controller/ConfigController.php
  src/Resources/public/js/configuration/graphql/configItem.js
  src/Resources/translations/admin.en.yml
  src/Service/CheckConsumerPermissionsService.php
  tests/_support/Resources/configuration_query_mutation_allowed.json
Labels: Improvement

#569 [Bug]: Cannot use concatenator on attributes in object bricks because of null value exception.
  src/GraphQL/Query/Operator/Concatenator.php
Labels: Bug

#572 [Bug]: thumbnail resolutions multiple types list doesn't work anymore
  src/GraphQL/FieldHelper/AbstractFieldHelper.php
Labels: Bug

#573 [Feature]: Implement "getTranslation" and filter for languages
  composer.json
  doc/10_GraphQL/04_Query/11_Query_Samples/10_Sample_GetTranslation.md
  doc/Installation_and_Upgrade/02_Upgrade_Notes.md
  src/Controller/ConfigController.php
  src/GraphQL/Query/QueryType.php
  src/GraphQL/Resolver/QueryType.php
  src/GraphQL/Resolver/TranslationListing.php
  src/Resources/translations/admin.en.yml
  tests/GraphQL/ResolveTest.php
Labels: New Feature
