Repository pimcore/data-hub, pull requests merged in 2022-04, with the labels that each got.

#509 Setup Test infrastructure and Tests
  .github/ci/files/.env
  .github/ci/pimcore_x/files/.env
  .github/ci/pimcore_x/files/.my.cnf
  .github/ci/pimcore_x/files/bin/console
  .github/ci/pimcore_x/files/config/config.yaml
  .github/ci/pimcore_x/files/config/packages/security.yaml
  .github/ci/pimcore_x/files/config/packages/test/config.yaml
  .github/ci/pimcore_x/files/config/routes/test/routes.yaml
  .github/ci/pimcore_x/files/config/services.yaml
  .github/ci/pimcore_x/files/config/system.yml
  .github/ci/pimcore_x/files/extensions.template.php
  .github/ci/pimcore_x/files/kernel/Kernel.php
  .github/ci/pimcore_x/files/public/.htaccess
  .github/ci/pimcore_x/files/public/index_test.php
  .github/ci/pimcore_x/files/templates/.gitkeep
  .github/ci/scripts/setup-pimcore-environment.sh
  .github/ci/scripts/setup-pimcore-x-environment.sh
  .github/workflows/codeception_pimcore_x.yml
  .github/workflows/static-analysis.yml
  codeception.dist.yml
  composer.json
  tests/GraphQL.suite.yml
  tests/GraphQL/Traits/ElementIdentificationTraitTest.php
  tests/Model.suite.yml
  tests/Model/ImportingConfigTest.php
  tests/Model/_bootstrap.php
  tests/Service.suite.dist.yml
  tests/Service/CheckConsumerPermissionsServiceTest.php
  tests/Service/OutputCacheServiceTest.php
  tests/Service/_bootstrap.php
  tests/_bootstrap.php
  tests/_support/GraphQLTester.php
  tests/_support/Helper/Model.php
  tests/_support/Helper/Unit.php
  tests/_support/ModelTester.php
  tests/_support/Resources/class_DataHubTestEntity_import.json
  tests/_support/Resources/configuration_query_mutation_allowed.json
  tests/_support/ServiceTester.php
  tests/_support/Test/ModelTestCase.php
  tests/_support/Test/TestCase.php
Labels: Improvement, Task

#500 Mutation datatype 'quantityValue' not supported yet
  doc/10_GraphQL/07_Mutation/20_DataObject_Mutations.md
  src/GraphQL/DataObjectInputProcessor/QuantityValue.php
  src/GraphQL/DataObjectMutationFieldConfigGenerator/QuantityValue.php
  src/GraphQL/DataObjectType/QuantityValueInputType.php
  src/Resources/config/graphql.yml
Labels: New Feature

#511 [BUG][php8.1] isset if label not exists
  src/GraphQL/DataObjectQueryOperatorConfigGenerator/Base.php
  src/GraphQL/FieldHelper/DataObjectFieldHelper.php
Labels: Bug

#501 [Improvement]: disable introspection by default for production environment
  src/Controller/WebserviceController.php
  src/Resources/public/js/configuration/graphql/configItem.js
  src/Resources/translations/admin.en.yml
Labels: Improvement

#515 Update README.md
  doc/10_GraphQL/README.md
Labels: Improvement

#521 [Bug]: Same fieldname in fieldcollection as in object itsself doesn't work
  src/GraphQL/Service.php
Labels: Bug

#522 [Bug]: GraphQL returns error when ElementCounter has no objects to count
  src/GraphQL/Query/Operator/ElementCounter.php
Labels: Bug
