Repository pimcore/data-hub, pull requests merged in 2022-12, with the labels that each got.

#641 [Task]: Remove o_ prefix for data object properties and database columns
  doc/10_GraphQL/10_Events.md
  src/GraphQL/Resolver/QueryType.php
Labels: Task

#645 [Bug]: Check create, update and new mutation for undefined array keys
  src/GraphQL/Mutation/MutationType.php
Labels: Bug

#649 [Bug][Docs]: getAssets is in the docu, but does not exist as a query object
  doc/10_GraphQL/04_Query/04_Asset_Queries.md
Labels: Bug

#634 [New Feature] Support Link datatype in mutations
  doc/10_GraphQL/07_Mutation/20_DataObject_Mutations.md
  src/GraphQL/DataObjectInputProcessor/Link.php
  src/GraphQL/DataObjectMutationFieldConfigGenerator/Link.php
  src/GraphQL/DataObjectType/LinkInputType.php
  src/GraphQL/DataObjectType/LinkType.php
  src/GraphQL/Resolver/Link.php
  src/Resources/config/graphql.yml
Labels: Improvement

#650 Improve: add codeception/module-symfony
  composer.json
Labels: Task

#658 Minor doc fixes
  doc/10_GraphQL/04_Query/11_Query_Samples/24_Sample_Fieldcollections.md
  doc/10_GraphQL/README.md
Labels: Task
