Repository pimcore/data-hub, pull requests merged in 2022-11, with the labels that each got.

#621 [Bug]: Query an asset by id throws an exception
  src/WorkspaceHelper.php
Labels: Bug

#624 [Improvement]: Use ContainerBagInterface instead of ContainerInterface
  doc/Installation_and_Upgrade/02_Upgrade_Notes.md
  src/Resources/config/services.yml
  src/Service/OutputCacheService.php
  tests/Service/OutputCacheServiceTest.php
  tests/_support/Helper/Service.php
Labels: Improvement

#625 [Task]: Quote plugin_datahub_workspaces_x column identifiers that are the same as protected keywords
  src/Configuration/Workspace/Dao.php
Labels: Task

#628 [TASK]: Add command for LocationAwareConfigRepository and remove loadLegacyConfigCallback
  doc/Installation_and_Upgrade/02_Upgrade_Notes.md
  src/Command/Configuration/MigrateLegacyConfig.php
  src/Configuration/Dao.php
Labels: Task

#632 [Bug]: JsonType doesn't work with 11.x
  src/GraphQL/SharedType/JsonType.php
Labels: Bug

#630 [Tests] Add support for codeception 5
  .github/workflows/codeception_pimcore_x.yml
  codeception.dist.yml
  composer.json
  tests/GraphQL.suite.yml
  tests/GraphQL/ResolveTest.php
  tests/GraphQL/Traits/ElementIdentificationTraitTest.php
  tests/Model.suite.yml
  tests/Model/ImportingConfigTest.php
  tests/Service.suite.dist.yml
  tests/Service/CheckConsumerPermissionsServiceTest.php
  tests/Service/OutputCacheServiceTest.php
  tests/_bootstrap.php
  tests/_support/Helper/Model.php
  tests/_support/Helper/Service.php
  tests/_support/Test/ModelTestCase.php
  tests/_support/Test/TestCase.php
Labels: Task

#629 [Improvement]: Add PhpStan for Pimcore 11 and fix possible errors
  .github/workflows/static-analysis.yml
  composer.json
Labels: Improvement

#633 [Bug] Fix Undefined array key Warning when a mutation has no column config yet
  src/Configuration.php
  src/GraphQL/Mutation/MutationType.php
Labels: Bug

#638 [Task]: Apply native parameter and return type hints
  src/Configuration.php
  src/Configuration/Dao.php
  src/Event/GraphQL/Model/ExecutorEvent.php
  src/Event/GraphQL/Model/OutputCachePreLoadEvent.php
  src/Event/GraphQL/Model/OutputCachePreSaveEvent.php
  src/Installer.php
  src/Migrations/PimcoreX/Version20210305134111.php
  src/PimcoreDataHubBundle.php
  tests/GraphQL/ResolveTest.php
  tests/_support/Helper/Model.php
Labels: Task

#640 [Task]: Bump pimcore version to 10.6
  .github/workflows/codeception_pimcore_x.yml
  .github/workflows/static-analysis.yml
  composer.json
Labels: Task
