Repository pimcore/data-hub, pull requests merged in 2023-01, with the labels that each got.

#661 [Task]: Replaced deprecated `Service::getType()` method, fix codeception and phpstan tests
  .github/workflows/codeception_pimcore_x.yml
  src/Configuration/Dao.php
  src/GraphQL/DataObjectQueryFieldConfigGenerator/Helper/ImageGallery.php
  src/Installer.php
Labels: Task

#665 [Bug]: Translation Schema error - expected element.id
  src/GraphQL/TranslationType/TranslationType.php
Labels: Bug

#673 [Task]: Add void return type
  tests/_support/Helper/Model.php
Labels: Task

#664 [Feature]: Video Asset - Dimension and duration
  src/GraphQL/AssetType/AssetType.php
  src/GraphQL/Resolver/AssetType.php
Labels: Improvement

#671 Deprecate merge operator
  src/GraphQL/DataObjectQueryOperatorConfigGenerator/Merge.php
  src/GraphQL/DataObjectType/MergeType.php
  src/GraphQL/Query/Operator/Merge.php
  src/GraphQL/Resolver/Merge.php
  src/Resources/public/js/queryoperator/Merge.js
Labels: Task

#675 Doc fixes
  doc/10_GraphQL/README.md
Labels: Task

#652 [New Feature] Support ImageGallery datatype in mutations
  doc/10_GraphQL/07_Mutation/20_DataObject_Mutations.md
  src/GraphQL/DataObjectInputProcessor/ImageGallery.php
  src/GraphQL/DataObjectMutationFieldConfigGenerator/ImageGallery.php
  src/Resources/config/graphql.yml
Labels: Improvement
