Repository pimcore/data-hub, pull requests merged in 2023-05, with the labels that each got.

#738 [Bug] [1.x with Pimcore 10.6] Creating new configs fails
  src/Configuration/Dao.php
Labels: Bug

#739 [Task]: Add childs to children migration
  src/Migrations/PimcoreX/Version20230503165847.php
Labels: Task

#716 [Improvement]: Option to disable GraphQL introspection via config
  doc/01_Installation_and_Upgrade/01_Upgrade_Notes.md
  doc/10_GraphQL/01_Configuration/03_Security_Settings.md
  src/Controller/WebserviceController.php
  src/DependencyInjection/Configuration.php
  src/EventListener/AdminListener.php
  src/Resources/config/eventlistener.yml
  src/Resources/public/js/configuration/graphql/configItem.js
Labels: Improvement

#744 Update typo
  doc/10_GraphQL/README.md
Labels: Bug

#734 Fix: Block fields in object bricks are always output as null even though they are filled
  src/GraphQL/DataObjectQueryFieldConfigGenerator/Block.php
  src/GraphQL/Service.php
Labels: Bug

#730 [Improvement]: Added replace table option and multi row update
  src/GraphQL/DataObjectInputProcessor/Table.php
  src/GraphQL/DataObjectMutationFieldConfigGenerator/Table.php
Labels: Improvement

#745 fix configuration storage config
  doc/20_Deployment.md
Labels: Task

#748 fix last migration in installer
  src/Installer.php
Labels: Bug

#750 [Task] Pre Release Todo
  composer.json
Labels: Task

#752 🔄 synced file(s) with pimcore/sync-common-files
  .gitattributes
Labels: sync
