Repository pimcore/data-hub, pull requests merged in 2023-02, with the labels that each got.

#681 [Bug]: Use t() method for operator text
  src/GraphQL/Resolver/Element.php
  src/Resources/public/js/queryoperator/Merge.js
  src/Resources/translations/admin.en.yml
Labels: Bug

#676 [Feature] Add ability to import/export datahub configurations
  doc/Installation_and_Upgrade/02_Upgrade_Notes.md
  phpstan-baseline.neon
  phpstan.neon
  src/Configuration.php
  src/Controller/ConfigController.php
  src/DependencyInjection/Configuration.php
  src/Resources/config/config.yml
  src/Resources/config/doctrine_migrations.yml
  src/Resources/config/pimcore/config.yaml
  src/Resources/config/services.yml
  src/Resources/public/js/config.js
  src/Resources/public/js/configuration/graphql/configItem.js
  src/Resources/translations/admin.en.yml
  src/Service/ExportService.php
  src/Service/ImportService.php
Labels: New Feature

#678 [Task] Add pimcore 10 and 11 support for new menu creation
  src/Resources/public/css/icons.css
  src/Resources/public/js/datahub.js
Labels: Improvement, Task

#687 [Bug]: Some Operators don't work
  phpstan-baseline.neon
  src/Controller/WebserviceController.php
  src/GraphQL/DataObjectType/MergeType.php
  src/GraphQL/Query/Operator/Concatenator.php
  src/GraphQL/Query/Operator/Substring.php
  src/GraphQL/Query/Operator/Trimmer.php
  src/GraphQL/Query/Value/DefaultValue.php
  src/GraphQL/Resolver/Merge.php
  src/Resources/public/js/queryoperator/ThumbnailHtml.js
Labels: Bug

#683 Bugfix: Support multiple filter conditions.
  src/GraphQL/Helper.php
Labels: Bug

#692 Refactor test directory
  .github/ci/files/.env
  .github/ci/files/.my.cnf
  .github/ci/files/bin/console
  .github/ci/files/config/bundles.php
  .github/ci/files/config/config.yaml
  .github/ci/files/config/packages/security.yaml
  .github/ci/files/config/packages/test/config.yaml
  .github/ci/files/config/services.yaml
  .github/ci/files/config/system.yml
  .github/ci/files/kernel/Kernel.php
  .github/ci/files/public/.htaccess
  .github/ci/files/public/index_test.php
  .github/ci/files/templates/.gitkeep
  .github/ci/scripts/setup-environment.sh
  .github/ci/scripts/setup-pimcore-x-environment.sh
  .github/workflows/codeception.yml
  .github/workflows/static-analysis.yml
  tests/bin/init-tests.sh
Labels: Task

#693 🔄 synced file(s) with pimcore/sync-common-files
  .github/ci/files/.env
  .github/ci/files/.env.test
  .github/ci/files/.my.cnf
  .github/ci/files/config/packages/security.yaml
  .github/ci/files/config/system.yml
  .github/ci/scripts/setup-environment.sh
  composer.json
Labels: sync

#690 Replace SensioFramework Cache annotation
  src/Controller/GraphQLExplorerController.php
Labels: Task

#686 [Feature]: Asset: Expose Embedded Meta Info
  doc/10_GraphQL/04_Query/11_Query_Samples/12_Sample_Asset_Metadata.md
  doc/img/graphql/asset_embeddedMetaInfo.png
  src/GraphQL/AssetType/AssetEmbeddedMetaInfoItem.php
  src/GraphQL/AssetType/AssetType.php
  src/GraphQL/Resolver/AssetType.php
  src/Resources/config/graphql.yml
Labels: Improvement

#682 Add published field to Document fields
  src/GraphQL/DocumentType/AbstractDocumentType.php
Labels: Improvement

#651 [New Feature] Support Table datatype in mutations
  doc/10_GraphQL/07_Mutation/20_DataObject_Mutations.md
  src/GraphQL/DataObjectInputProcessor/Table.php
  src/GraphQL/DataObjectMutationFieldConfigGenerator/Table.php
  src/Resources/config/graphql.yml
Labels: Improvement

#696 [Bug]: Change highlighting in responses from graphql to json where appropriate
  doc/10_GraphQL/04_Query/10_Filtering.md
  doc/10_GraphQL/04_Query/11_Query_Samples/05_Sample_Element_Properties.md
  doc/10_GraphQL/04_Query/11_Query_Samples/08_ClassificationStore.md
  doc/10_GraphQL/04_Query/11_Query_Samples/12_Sample_Asset_Metadata.md
  doc/10_GraphQL/04_Query/11_Query_Samples/21_Sample_ManyToMany_Object_Relation.md
  doc/10_GraphQL/04_Query/11_Query_Samples/24_Sample_Fieldcollections.md
  doc/10_GraphQL/04_Query/11_Query_Samples/25_Sample_Parent_Children_Siblings.md
  doc/10_GraphQL/04_Query/11_Query_Samples/26_Sample_Get_Linked_Data.md
  doc/10_GraphQL/04_Query/11_Query_Samples/27_Sample_Translate_Values.md
Labels: Task

#695 [Bug][Installer] Don't silently catch errors during install
  src/Installer.php
Labels: Bug

#698 [Task] Substitute deprecated set/getObject method
  src/GraphQL/DocumentResolver/Email.php
  src/GraphQL/Mutation/MutationType.php
Labels: Task

#699 Added missing return type
  composer.json
  src/Configuration.php
Labels: Task

#700 Adapt system.yml - related to https://github.com/pimcore/pimcore/pull/14276
  .github/ci/files/config/system.yml
Labels: sync
