Repository pimcore/data-hub, pull requests merged in 2024-10, with the labels that each got.

#876 Generate static typename for element metadata key value pairs
  src/GraphQL/DataObjectType/ElementMetadataKeyValuePairInputType.php
  src/GraphQL/DataObjectType/ElementMetadataKeyValuePairType.php
Labels: Improvement, Pimcore:ToDo

#896 Do not store CORS headers in output cache
  doc/10_GraphQL/10_Events.md
  src/Controller/WebserviceController.php
  src/Service/OutputCacheService.php
Labels: Bug

#898 [Bug]: Import of Data Importer configuration
  src/Controller/ConfigController.php
  src/Resources/public/js/config.js
Labels: Bug

#901 [Bug]: GraphQL - Using Fragment inside Inline Fragment returns only null values
  src/GraphQL/FieldHelper/AbstractFieldHelper.php
Labels: Bug, Pimcore:ToDo

#902 [Improvement]: Retrieving thumbnail URLs via GraphQL API triggers thumbnail generation
  doc/10_GraphQL/04_Query/04_Asset_Queries.md
  src/GraphQL/AssetType/AssetType.php
  src/GraphQL/FieldHelper/AssetFieldHelper.php
  src/GraphQL/Resolver/AssetType.php
Labels: Improvement

#893 [Bug]: Fix playground autoComplete visual problem
  src/Resources/views/Feature/explorer.html.twig
Labels: Third Party Bug, Pimcore:ToDo

#900 Use factory for Pimcore object type instead static call.
  src/GraphQL/ClassTypeDefinitions.php
  src/GraphQL/DataObjectTypeFactory.php
  src/GraphQL/Service.php
  src/Resources/config/graphql.yml
Labels: Pimcore:ToDo

#907 [Feature]: Disabling of language fallback
  doc/10_GraphQL/04_Query/08_Localization.md
  src/GraphQL/DataObjectQueryFieldConfigGenerator/Base.php
  src/GraphQL/FieldHelper/DataObjectFieldHelper.php
Labels: New Feature
