Repository pimcore/data-hub, pull requests merged in 2024-11, with the labels that each got.

#908 [Task] Add documentation for aliases
  doc/10_GraphQL/04_Query/06_Operators.md
  doc/10_GraphQL/04_Query/11_Using_Aliases.md
Labels: Task

#910 Fix regression from #875
  src/GraphQL/Service.php
Labels: Pimcore:ToDo

#914 [Bug]: Creating or Updating advanced many-to-many relationship fails when more than one relation
  src/GraphQL/DataObjectInputProcessor/AdvancedManyToManyRelation.php
Labels: Bug

#917 [Bug]: Newly added operators not working anymore
  src/Resources/public/js/fieldConfigDialog.js
  src/Resources/public/js/queryvalue/DefaultValue.js
Labels: Bug

#912 Added CsFeature title
  src/GraphQL/ClassificationstoreFeatureType/Helper.php
  src/GraphQL/TypeInterface/CsFeature.php
Labels: Improvement, Pimcore:ToDo

#916 Allow cloning even if record is not writeable
  src/Resources/public/js/config.js
Labels: Pimcore:ToDo
