Repository pimcore/data-hub, pull requests merged in 2025-03, with the labels that each got.

#950 Allow setting Date and DateTime-fields to empty / null even if the fieldtype is DATETIME
  src/GraphQL/DataObjectInputProcessor/Date.php
Labels: Bug

#952 [Task] Remove BC Layer for DataObject Service (getVersionDependentDatabaseColumnName)
  src/GraphQL/Resolver/QueryType.php
Labels: Task

#954 Change collation from utf8mb4_general_ci to utf8mb4_unicode_520_ci
  src/Installer.php
Labels: Task

#956 [Improvement]: Support DBAL v4
  tests/_support/Helper/Model.php
Labels: Improvement, Pimcore:Priority

#927 Getting instance ElementMetadataKeyValuePairType instead creating new.
  src/GraphQL/DataObjectType/MultihrefMetadataType.php
  src/GraphQL/DataObjectType/ObjectMetadataType.php
Labels: Pimcore:ToDo, External

#944 Add concept of IsValidDataObjectTriggerEvent.
  src/Event/IsValidDataObjectTriggerEvent.php
Labels: Improvement, Pimcore:Backlog
