Repository pimcore/data-hub, pull requests merged in 2025-02, with the labels that each got.

#935 [Task] Remove deprecations
  doc/01_Installation_and_Upgrade/01_Upgrade_Notes.md
  doc/10_GraphQL/08_Operators/Query/Merge.md
  doc/10_GraphQL/10_Events.md
  phpstan-baseline.neon
  src/Command/GraphQL/RebuildDefinitionsCommand.php
  src/Configuration.php
  src/Configuration/Dao.php
  src/Configuration/DatahubConfigLocator.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/PimcoreDataHubExtension.php
  src/GraphQL/DataObjectQueryOperatorConfigGenerator/Merge.php
  src/GraphQL/DataObjectType/MergeType.php
  src/GraphQL/Query/Operator/Merge.php
  src/GraphQL/Resolver/Merge.php
  src/GraphQL/Resolver/QueryType.php
  src/PimcoreDataHubBundle.php
  src/Resources/config/graphql.yml
  src/Resources/public/js/configuration/graphql/configItem.js
  src/Resources/public/js/queryoperator/Merge.js
  src/Resources/translations/admin.en.yml
Labels: Task

#883 Added field type for table query type definition
  src/GraphQL/DataObjectQueryFieldConfigGenerator/AbstractTable.php
Labels: BC-BREAK, Improvement, Pimcore:ToDo, Pimcore:Priority, External

#936 [Task] Update 01_Upgrade_Notes.md
  doc/01_Installation_and_Upgrade/01_Upgrade_Notes.md
Labels: Task

#937 [Bug] Introduce numeric-prefix for table
  src/GraphQL/DataObjectQueryFieldConfigGenerator/Table.php
Labels: Bug

#941 [Task] Update workflows to centralized approach
  .github/ci/scripts/setup-pimcore-environment.sh
  .github/workflows/codeception.yml
  .github/workflows/static-analysis.yml
Labels: Task, Pimcore:ToDo

#943 [Docs] cleanup installation instructions
  doc/01_Installation_and_Upgrade/README.md
Labels: Task

#945 [Task] Add container extension
  src/PimcoreDataHubBundle.php
Labels: Task, Pimcore:ToDo
